-- MySQL Script generated by MySQL Workbench
-- Thu Aug  1 12:39:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vrinfinity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vrinfinity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vrinfinity` DEFAULT CHARACTER SET utf8 ;
USE `vrinfinity` ;

-- -----------------------------------------------------
-- Table `vrinfinity`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `role` VARCHAR(5) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`service` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `formula` VARCHAR(16) NOT NULL DEFAULT '00H-00M-0VR-0SH',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`visit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(32) NOT NULL,
  `start` TIMESTAMP NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_visit_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_visit_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `vrinfinity`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`text_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`text_news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `next_id` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtext_news_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`image_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`image_news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(127) NOT NULL,
  `next_id` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL,
  `subject` VARCHAR(127) NOT NULL,
  `image_news_id` INT UNSIGNED NOT NULL,
  `text_news_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_news_image_news1_idx` (`image_news_id` ASC) VISIBLE,
  INDEX `fk_news_text_news1_idx` (`text_news_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_image_news1`
    FOREIGN KEY (`image_news_id`)
    REFERENCES `vrinfinity`.`image_news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_text_news1`
    FOREIGN KEY (`text_news_id`)
    REFERENCES `vrinfinity`.`text_news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`game_vr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`game_vr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  `text` VARCHAR(511) NOT NULL,
  `image` VARCHAR(127) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`reset_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`reset_password` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(32) NOT NULL,
  `new_password` VARCHAR(127) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`visits_vr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`visits_vr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NOT NULL,
  `visit_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_visits_smallhall_visit2_idx` (`visit_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_smallhall_visit2`
    FOREIGN KEY (`visit_id`)
    REFERENCES `vrinfinity`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vrinfinity`.`visits_smallhall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrinfinity`.`visits_smallhall` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NOT NULL,
  `visit_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_visits_smallhall_visit1_idx` (`visit_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_smallhall_visit1`
    FOREIGN KEY (`visit_id`)
    REFERENCES `vrinfinity`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
